ARG BUILDER_VERSION=latest
ARG REPOSITORY_COMMIT_HASH

# stage 1: build extension.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG BUILDER_VERSION
ARG REPOSITORY_COMMIT_HASH

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      git \
      make \
    && dnf clean all

WORKDIR /inputmethod-shortcuts
COPY ./patches /tmp/patches
RUN git init \
    && git remote add origin https://github.com/osamuaoki/inputmethod-shortcuts \
    && git fetch origin "${REPOSITORY_COMMIT_HASH}" --depth=1 \
    && git checkout FETCH_HEAD \
    && git apply /tmp/patches/*.patch

RUN make INSTALL_PATH=./dist install

# stage 2: copy extension to distribution container.
FROM scratch

COPY --from=builder \
    /inputmethod-shortcuts/dist \
    /usr/share/gnome-shell/extensions/inputmethod-shortcuts@osamu.debian.org
