#!/usr/bin/env bash

set -o "errexit" -o "nounset" -o "pipefail"

GPG_SOCKET_DIR=$(gpgconf --list-dirs socketdir)

find "${XDG_CONFIG_HOME:-${HOME}/.config}/systemd/user" \
  -type "d" \
  -name "gpg-agent*.socket.d" \
  -print \
| while read -r TARGET; do \
    sed --expression="s|ListenStream=%t/gnupg|ListenStream=${GPG_SOCKET_DIR}|" --in-place "${TARGET}/override.conf"
  done

systemctl --user daemon-reload
