version: 2

updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "Asia/Tokyo"
    labels:
      - "Type: CI"
      - "Type: Dependencies"
    assignees:
      - "RShirohara"
