ARG BUILDER_VERSION=latest
ARG REPOSITORY_VERSION

# stage 1: build script.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG BUILDER_VERSION
ARG REPOSITORY_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
        git \
        nodejs \
        nodejs-npm \
    && dnf clean all

RUN git clone https://github.com/GnomeSnapExtensions/gSnap \
        --branch="${REPOSITORY_VERSION}" \
        --depth=1

WORKDIR /gSnap
RUN npm install \
    && npm run build

# stage 2: copy extensions.
FROM scratch

COPY --from=builder \
    /gSnap/dist \
    /usr/share/gnome-shell/extensions/gSnap@micahosborne
