ARG BUILDER_VERSION
ARG REPOSITORY_VERSION

# stage 1: build theme.
FROM registry.fedoraproject.org/fedora:${BUILDER_VERSION} as builder
ARG REPOSITORY_VERSION

RUN dnf install --assumeyes \
        git \
        which \
        sassc \
        glib2-devel

RUN git clone https://github.com/vinceliuice/WhiteSur-gtk-theme \
        --branch="${REPOSITORY_VERSION}" \
        --depth=1

RUN /WhiteSur-gtk-theme/install.sh \
        --dest /usr/share/themes \
        --silent-mode

# stage 2: copy theme files.
FROM scratch

COPY --from=builder \
    /usr/share/themes \
    /usr/share/themes
