ARG BUILDER_VERSION=latest
ARG REPOSITORY_VERSION

# stage 1: fetch module.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG BUILDER_VERSION
ARG REPOSITORY_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      git \
    && dnf clean all

RUN git clone https://github.com/secureblue/secureblue \
      --branch="${REPOSITORY_VERSION}" \
      --depth=1

# stage 2: copy module to distribution container.
FROM scratch AS dist

COPY --from=builder \
    /secureblue/modules/secureblue-signing \
    /modules/secureblue-signing
