ARG BUILDER_VERSION=42
ARG REPOSITORY_VERSION=v0.9.1

# stage 1: build script.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG BUILDER_VERSION
ARG REPOSITORY_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      git \
      kf6-kpackage \
    && dnf clean all

RUN git clone https://github.com/Latgardi/darwinmenu \
      --branch="${REPOSITORY_VERSION}" \
      --depth=1

WORKDIR /darwinmenu
RUN kpackagetool6 --packageroot=/darwinmenu/dist --install=./package

# stage 2: copy script to distribution container.
FROM scratch AS dist

COPY --from=builder \
    /darwinmenu/dist \
    /usr/share/plasma/plasmoids/
