ARG BUILDER_VERSION=latest
ARG REPOSITORY_VERSION

# stage 1: build theme.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG REPOSITORY_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      fedora-workstation-backgrounds \
      file \
      gdm \
      git \
      glib2-devel \
      ImageMagick \
      sassc \
      sudo \
      which \
    && dnf clean all

RUN git clone https://github.com/vinceliuice/WhiteSur-gtk-theme \
      --branch="${REPOSITORY_VERSION}" \
      --depth=1

WORKDIR /WhiteSur-gtk-theme
# Install themes.
RUN USER=root ./install.sh \
      --dest /usr/share/themes \
      --silent-mode \
# Install GDM theme.
    && USER=root ./tweaks.sh \
      --color dark \
      --gdm \
      -background "/usr/share/backgrounds/fedora-workstation/glasscurtains_dark.webp" \
      --silent-mode \
# Install dash-to-dock theme.
    && mkdir --parents \
      /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com \
    && sed \
      --expression="336 s|fix_dash_to_dock|install_dash_to_dock_theme|" \
      --in-place ./tweaks.sh \
    && sed \
      --expression="810 s|\"sudo\"$||" \
      --expression="812 s|sudo ||" \
      --in-place ./libs/lib-install.sh \
    && USER=root ./tweaks.sh \
      --dash-to-dock \
      --silent-mode

# stage 2: copy theme to distribution container.
FROM scratch AS dist

COPY --from=builder \
    /usr/share/themes/WhiteSur-Dark \
    /usr/share/themes/WhiteSur-Dark
COPY --from=builder \
    /usr/share/themes/WhiteSur-Dark-hdpi \
    /usr/share/themes/WhiteSur-Dark-hdpi
COPY --from=builder \
    /usr/share/themes/WhiteSur-Dark-solid \
    /usr/share/themes/WhiteSur-Dark-solid
COPY --from=builder \
    /usr/share/themes/WhiteSur-Dark-solid-hdpi \
    /usr/share/themes/WhiteSur-Dark-solid-hdpi
COPY --from=builder \
    /usr/share/themes/WhiteSur-Dark-solid-xhdpi \
    /usr/share/themes/WhiteSur-Dark-solid-xhdpi
COPY --from=builder \
    /usr/share/themes/WhiteSur-Dark-xhdpi \
    /usr/share/themes/WhiteSur-Dark-xhdpi
COPY --from=builder \
    /usr/share/themes/WhiteSur-Light \
    /usr/share/themes/WhiteSur-Light
COPY --from=builder \
    /usr/share/themes/WhiteSur-Light-hdpi \
    /usr/share/themes/WhiteSur-Light-hdpi
COPY --from=builder \
    /usr/share/themes/WhiteSur-Light-solid \
    /usr/share/themes/WhiteSur-Light-solid
COPY --from=builder \
    /usr/share/themes/WhiteSur-Light-solid-hdpi \
    /usr/share/themes/WhiteSur-Light-solid-hdpi
COPY --from=builder \
    /usr/share/themes/WhiteSur-Light-solid-xhdpi \
    /usr/share/themes/WhiteSur-Light-solid-xhdpi
COPY --from=builder \
    /usr/share/themes/WhiteSur-Light-xhdpi \
    /usr/share/themes/WhiteSur-Light-xhdpi
COPY --from=builder \
    /usr/share/gnome-shell/gnome-shell-theme.gresource \
    /usr/share/themes/WhiteSur-Extension/gdm/gnome-shell-theme.gresource
COPY --from=builder \
    /usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/stylesheet.css \
    /usr/share/themes/WhiteSur-Extension/dash-to-dock/stylesheet.css
