ARG BUILDER_VERSION=latest
ARG REPOSITORY_VERSION

# stage 1: build theme.
FROM registry.fedoraproject.org/fedora:${BUILDER_VERSION} AS builder
ARG REPOSITORY_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
        git \
        which \
        sassc \
        glib2-devel \
    && dnf clean all

RUN git clone https://github.com/vinceliuice/WhiteSur-gtk-theme \
        --branch="${REPOSITORY_VERSION}" \
        --depth=1

WORKDIR /WhiteSur-gtk-theme
RUN USER=root ./install.sh \
        --dest /usr/share/themes \
        --silent-mode

# stage 2: copy theme files.
FROM scratch

COPY --from=builder \
    /usr/share/themes \
    /usr/share/themes
