ARG BUILDER_VERSION=43
ARG REPOSITORY_COMMIT_HASH=e190baf618ed95ee217d2fd45589bd309b37672b

# stage 1: build icons.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG REPOSITORY_COMMIT_HASH

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      git \
    && dnf clean all

WORKDIR /WhiteSur-cursors
RUN git init \
    && git remote add origin https://github.com/vinceliuice/WhiteSur-cursors \
    && git fetch origin "${REPOSITORY_COMMIT_HASH}" --depth=1 \
    && git checkout FETCH_HEAD

RUN /WhiteSur-cursors/install.sh

# stage 2: copy icons to distribution container.
FROM scratch AS dist

COPY --from=builder \
    /usr/share/icons/WhiteSur-cursors \
    /usr/share/icons/WhiteSur-cursors
