ARG BUILD_BUILDER_VERSION=latest
ARG BUILD_REPOSITORY_COMMIT_HASH

# stage 1: build theme.
FROM registry.fedoraproject.org/fedora-minimal:${BUILD_BUILDER_VERSION} AS builder
ARG BUILD_REPOSITORY_COMMIT_HASH

RUN dnf install --assumeyes \
        git

WORKDIR /WhiteSur-cursors
RUN git init \
    && git remote add origin https://github.com/vinceliuice/WhiteSur-cursors \
    && git fetch origin "${BUILD_REPOSITORY_COMMIT_HASH}" --depth=1 \
    && git checkout FETCH_HEAD

RUN /WhiteSur-cursors/install.sh

# stage 2: copy theme files.
FROM scratch

COPY --from=builder \
    /usr/share/icons \
    /usr/share/icons
