ARG BUILDER_VERSION=42
ARG RELEASE_VERSION=4.10.2891.0

# stage 1: download resource.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG RELEASE_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      jq \
      unzip \
    && dnf clean all

WORKDIR /widevine-cdm
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl \
      --location \
      --output ./widevine.zip \
      "https://dl.google.com/widevine-cdm/${RELEASE_VERSION}-linux-x64.zip" \
    && unzip ./widevine.zip \
    && jq 'del(.arch, .os) | ."x-cdm-supported-encryption-schemes" = ["cenc", "cbcs"] | .platforms.[0] = {"os": "linux", "arch": "x64", "sub_package_path": "_platform_specific/linux_x64/"} ' \
      ./manifest.json \
      > ./manifest.updated.json \
    && mv manifest.updated.json manifest.json \
    && install --directory --mode=755 ./dist/WidevineCdm/_platform_specific/linux_x64 \
    && install --mode=644 ./LICENSE.txt ./dist/WidevineCdm/ \
    && install --mode=644 ./manifest.json ./dist/WidevineCdm/ \
    && install --mode=755 ./libwidevinecdm.so ./dist/WidevineCdm/_platform_specific/linux_x64/

# stage 2: copy resource to distribution container.
FROM scratch AS dist

COPY --from=builder \
    /widevine-cdm/dist \
    /usr/lib64/trivalent
