ARG BUILDER_VERSION=42
ARG CHROME_MAJOR_VERSION=142

# stage 1: download resource.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG CHROME_MAJOR_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      fedora-workstation-repositories \
    && sed \
      --expression="s|^enabled=0$|enabled=1|" \
      --in-place /etc/yum.repos.d/google-chrome.repo \
    && dnf --setopt="install_weak_deps=False" install --assumeyes \
      "google-chrome-stable-${CHROME_MAJOR_VERSION}.*" \
    && dnf clean all

WORKDIR /widevine-cdm
RUN mkdir --parents ./dist \
    && cp --recursive \
      /opt/google/chrome/WidevineCdm \
      ./dist/

# stage 2: copy resource to distribution container.
FROM scratch AS dist

COPY --from=builder \
    /widevine-cdm/dist \
    /usr/lib64/trivalent
