#!/usr/bin/env bash
set -o "errexit" -o "nounset" -o "pipefail"

FLATPAK_OVERRIDE_DIR="${XDG_DATA_HOME:-${HOME}/.local/share}/flatpak/overrides"
if [[ ! -d "${FLATPAK_OVERRIDE_DIR}" ]]; then
  /usr/bin/mkdir --parents "${FLATPAK_OVERRIDE_DIR}"
fi

find /usr/share/grand-os/flatpak-override -type "f" \
| while read -r PATH; do \
    FILE_NAME="${PATH##*/}"
    if [[ ! -f "${FLATPAK_OVERRIDE_DIR}/${FILE_NAME}" ]]; then
      /usr/bin/cp "${PATH}" ${FLATPAK_OVERRIDE_DIR}
    fi
  done

ujust harden-flatpak
