ARG BUILDER_VERSION=latest
ARG REPOSITORY_VERSION
ARG KWIN_VERSION

# stage 1: build effect.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG BUILDER_VERSION
ARG REPOSITORY_VERSION
ARG KWIN_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
        git \
        cmake \
        gcc-c++ \
        extra-cmake-modules \
        kwin-devel-${KWIN_VERSION}-*.fc${BUILDER_VERSION} \
        kf6-kconfigwidgets-devel \
        libepoxy-devel \
        kf6-kcmutils-devel \
        kf6-ki18n-devel \
        qt6-qtbase-private-devel \
        wayland-devel \
    && dnf clean all

RUN git clone https://github.com/matinlotfali/KDE-Rounded-Corners \
        --branch="${REPOSITORY_VERSION}" \
        --depth=1

WORKDIR /KDE-Rounded-Corners
RUN cmake -B build \
    && cmake --build build -j \
    && DESTDIR="./dist" cmake --install build

# stage 2: copy effect to distribution container.
FROM scratch AS dist

COPY --from=builder \
    /KDE-Rounded-Corners/dist \
    /
