ARG BUILDER_VERSION=42
ARG REPOSITORY_VERSION=2024-11-18

# stage 1: build theme.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG REPOSITORY_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      git \
    && dnf clean all

RUN git clone https://github.com/vinceliuice/WhiteSur-kde \
      --branch="${REPOSITORY_VERSION}" \
      --depth=1

WORKDIR /WhiteSur-kde
RUN mkdir --parents /usr/share/sddm/themes \
    && ./install.sh --window "sharp" \
    && ./sddm/install.sh

# stage 2: copy theme to distribution container.
FROM scratch AS dist

COPY --from=builder \
    /usr/share/aurorae/themes \
    /usr/share/aurorae/themes
COPY --from=builder \
    /usr/share/color-schemes \
    /usr/share/color-schemes
COPY --from=builder \
    /usr/share/plasma/desktoptheme \
    /usr/share/plasma/desktoptheme
COPY --from=builder \
    /usr/share/plasma/look-and-feel \
    /usr/share/plasma/look-and-feel
COPY --from=builder \
    /usr/share/Kvantum \
    /usr/share/Kvantum
COPY --from=builder \
    /usr/share/wallpapers \
    /usr/share/wallpapers
COPY --from=builder \
    /usr/share/sddm/themes \
    /usr/share/sddm/themes
