ARG BUILDER_VERSION=42
ARG REPOSITORY_VERSION=2024-11-18

# stage 1: build theme.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG REPOSITORY_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      git \
    && dnf clean all

RUN git clone https://github.com/vinceliuice/WhiteSur-kde \
      --branch="${REPOSITORY_VERSION}" \
      --depth=1

WORKDIR /WhiteSur-kde
RUN mkdir --parents /usr/share/sddm/themes \
    && ./install.sh --color "dark" --window "sharp" \
    && ./sddm/install.sh

# stage 2: copy theme to distribution container.
FROM scratch AS dist

COPY --from=builder \
    /usr/share/aurorae/themes/WhiteSur-dark-sharp \
    /usr/share/aurorae/themes/WhiteSur-dark-sharp
COPY --from=builder \
    /usr/share/color-schemes/WhiteSurDark.colors \
    /usr/share/color-schemes/WhiteSurDark.colors
COPY --from=builder \
    /usr/share/plasma/desktoptheme/WhiteSur-dark \
    /usr/share/plasma/desktoptheme/WhiteSur-dark
COPY --from=builder \
    /usr/share/plasma/look-and-feel/com.github.vinceliuice.WhiteSur-dark \
    /usr/share/plasma/look-and-feel/com.github.vinceliuice.WhiteSur-dark
COPY --from=builder \
    /usr/share/Kvantum/WhiteSur/WhiteSurDark.kvconfig \
    /usr/share/Kvantum/WhiteSur/WhiteSurDark.svg \
    /usr/share/Kvantum/WhiteSur/
COPY --from=builder \
    /usr/share/wallpapers/WhiteSur-dark \
    /usr/share/wallpapers/WhiteSur-dark
COPY --from=builder \
    /usr/share/sddm/themes/WhiteSur-dark \
    /usr/share/sddm/themes/WhiteSur-dark
