ARG BUILDER_VERSION=latest
ARG REPOSITORY_VERSION

# stage 1: extract fonts.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG BUILDER_VERSION
ARG REPOSITORY_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      zip \
    && dnf clean all

WORKDIR /hackgen
RUN curl --location --output "./hackgen.zip" \
      "https://github.com/yuru7/Hackgen/releases/download/${REPOSITORY_VERSION}/HackGen_${REPOSITORY_VERSION}.zip" \
    && curl --location --output "./hackgen_nf.zip" \
      "https://github.com/yuru7/Hackgen/releases/download/${REPOSITORY_VERSION}/HackGen_NF_${REPOSITORY_VERSION}.zip"

RUN unzip hackgen.zip \
    && unzip hackgen_nf.zip

# stage 2: copy fonts to distribution container.
FROM scratch AS dist
ARG REPOSITORY_VERSION

COPY --from=builder \
    /hackgen/HackGen_${REPOSITORY_VERSION} \
    /usr/share/fonts/hackgen
COPY --from=builder \
    /hackgen/HackGen_NF_${REPOSITORY_VERSION} \
    /usr/share/fonts/hackgen
