ARG BUILDER_VERSION=latest
ARG REPOSITORY_VERSION

# stage 1: build script.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG BUILDER_VERSION
ARG REPOSITORY_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      git \
      make \
      zip \
    && dnf clean all

RUN git clone https://github.com/gerritdevriese/kzones \
      --branch="${REPOSITORY_VERSION}" \
      --depth=1

WORKDIR /kzones
RUN make build

# stage 2: copy script to distribution container.
FROM scratch AS dist

COPY --from=builder \
    /kzones/pkg \
    /usr/share/kwin/scripts/kzones
