#!/usr/bin/env bash

#MISE description="Lint containerfile."
#USAGE arg "<file>" help="Target file(s)." var=#true
#USAGE flag "-f --format <format>" help="Output format." default="tty"

set -o "errexit" -o "nounset" -o "pipefail"

# shellcheck disable=SC2086
hadolint --format="${usage_format:-}" ${usage_file:-}

