#!/usr/bin/env bash

#MISE description="Lint github-action workflow."
#USAGE arg "[file]" help="Target file(s)." var=#true
#USAGE flag "-f --format <format>" help="Output format" default="full" choices "full" "oneline"

set -o "errexit" -o "nounset" -o "pipefail"

flags=()
if [[ "${usage_format:-}" == "oneline" ]]; then
  flags=("${flags[@]}" "--oneline")
fi

# shellcheck disable=SC2086
actionlint "${flags[@]}" ${usage_file:-}
