ARG BUILDER_VERSION=latest
ARG REPOSITORY_VERSION

# stage 1: build resources for system package.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG REPOSITORY_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      cmake \
      gcc-c++ \
      git \
      qt5-qtbase-private-devel \
      qt5-qtbase-static \
      qt5-qtsvg-devel \
      qt5-qtwayland-devel \
      qt6-qtbase-private-devel \
      qt6-qtbase-static \
      qt6-qtsvg-devel \
      qt6-qtwayland-devel \
      wayland-devel \
    && dnf clean all

RUN git clone https://github.com/FengZhongShaoNian/QWhiteSurGtkDecorations \
      --branch="${REPOSITORY_VERSION}" \
      --depth=1

WORKDIR /QWhiteSurGtkDecorations
RUN cmake \
      -B build-qt5 \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DHAS_QT6_SUPPORT=true \
      -DUSE_QT6=false \
    && cmake --build ./build-qt5 -j \
    && DESTDIR="./dist" cmake --install ./build-qt5 \
    && cmake \
      -B build-qt6 \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DUSE_QT6=true \
    && cmake --build ./build-qt6 -j \
    && DESTDIR="./dist" cmake --install ./build-qt6

# stage 2: copy resources to distribution container.
FROM scratch AS dist

COPY --from=builder \
  /QWhiteSurGtkDecorations/dist \
  /
