ARG BUILDER_VERSION=latest
ARG REPOSITORY_VERSION

# stage 1: build resources for system package.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS system-builder
ARG REPOSITORY_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      cmake \
      gcc-c++ \
      git \
      qt5-qtbase-private-devel \
      qt5-qtbase-static \
      qt5-qtsvg-devel \
      qt5-qtwayland-devel \
      qt6-qtbase-private-devel \
      qt6-qtbase-static \
      qt6-qtsvg-devel \
      qt6-qtwayland-devel \
      wayland-devel \
    && dnf clean all

RUN git clone https://github.com/FengZhongShaoNian/QWhiteSurGtkDecorations \
      --branch="${REPOSITORY_VERSION}" \
      --depth=1

WORKDIR /QWhiteSurGtkDecorations
RUN cmake \
      -B build-qt5 \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DHAS_QT6_SUPPORT=true \
      -DUSE_QT6=false \
    && cmake --build ./build-qt5 -j \
    && DESTDIR="./dist" cmake --install ./build-qt5 \
    && cmake \
      -B build-qt6 \
      -DCMAKE_INSTALL_PREFIX=/usr \
      -DUSE_QT6=true \
    && cmake --build ./build-qt6 -j \
    && DESTDIR="./dist" cmake --install ./build-qt6

# stage 2: build resources for flatpak package.
## Runtime: 5.15-24.08
FROM ghcr.io/flathub-infra/flatpak-github-actions:kde-5.15-24.08 AS flatpak-builder-5.15-24.08
ARG REPOSITORY_VERSION
ENV RUNTIME_VERSION="5.15-24.08"
ENV QT_VERSION="qt5"

# WORKAROUND: generate machine-id
RUN uname -a \
    | md5sum \
    | cut --delimiter=" " --field=1 \
    > /etc/machine-id

COPY ./flatpak /QWhiteSurGtkDecorations
WORKDIR /QWhiteSurGtkDecorations
RUN sed \
      --expression="s|\${RUNTIME_VERSION}|${RUNTIME_VERSION}|g" \
      --expression="s|\${REPOSITORY_VERSION}|${REPOSITORY_VERSION}|" \
      --in-place "./org.kde.WaylandDecoration.QWhiteSurGtkDecorations.${QT_VERSION}.json" \
    && flatpak-builder \
      --verbose \
      --disable-rofiles-fuse \
      --force-clean \
      ./build \
      "./org.kde.WaylandDecoration.QWhiteSurGtkDecorations.${QT_VERSION}.json"

# stage 3: copy resources to distribution container.
# FROM scratch AS dist

# COPY --from=system-builder \
#   /QWhiteSurGtkDecorations/dist \
#   /
# COPY --from=flatpak-builder \
#   /QWhiteSurGtkDecorations/dist/output \
#   /
