#!/usr/bin/env bash

set -o "errexit" -o "nounset" -o "pipefail"

FLATPAK_BUNDLE_DIR="/usr/share/flatpak/bundles"

find "${FLATPAK_BUNDLE_DIR}" -type "f" -path "*.flatpak" -print \
| while read -r TARGET_PATH; do
    PACKAGE_NAME=$(
      basename "${TARGET_PATH}" ".flatpak" \
      | cut --delimiter="_" --fields=1
    )
    PACKAGE_BRANCH=$(
      basename "${TARGET_PATH}" ".flatpak" \
      | cut --delimiter="_" --fields=2 \
      | cut --delimiter="-" --fields=1
    )
    PACKAGE_REF="${PACKAGE_NAME}/$(arch)/${PACKAGE_BRANCH}"
    PACKAGE_INSTALLED=$(
      flatpak info "${PACKAGE_REF}" &> /dev/null
      echo "${?}"
    )
    if [[ "${PACKAGE_INSTALLED}" -eq 1 ]]; then
      flatpak install \
        --user \
        --bundle \
        --noninteractive \
        --or-update \
        "@"
    fi
  done
