ARG BUILDER_VERSION=latest
ARG REPOSITORY_VERSION

# stage 1: build icons.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG REPOSITORY_VERSION

RUN dnf install --assumeyes \
        git \
        gtk-update-icon-cache

RUN git clone https://github.com/vinceliuice/WhiteSur-icon-theme \
        --branch="${REPOSITORY_VERSION}" \
        --depth=1

RUN /WhiteSur-icon-theme/install.sh \
        --dest /usr/share/icons \
        --alternative

# stage 2: copy icon files.
FROM scratch

COPY --from=builder \
    /usr/share/icons \
    /usr/share/icons
