ARG BUILDER_VERSION=latest
ARG REPOSITORY_VERSION

# stage 1: build icons.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG REPOSITORY_VERSION

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      git \
      gtk-update-icon-cache \
    && dnf clean all

RUN git clone https://github.com/vinceliuice/WhiteSur-icon-theme \
      --branch="${REPOSITORY_VERSION}" \
      --depth=1

WORKDIR /WhiteSur-icon-theme
RUN ./install.sh \
      --dest /usr/share/icons \
      --alternative

# stage 2: copy icons to distribution container.
FROM scratch AS dist

COPY --from=builder \
    /usr/share/icons \
    /usr/share/icons
