ARG BUILDER_VERSION=42
ARG REPOSITORY_COMMIT_HASH=e7a351121706343abe7a164b625a55e245c16ab5

# stage 1: build extension.
FROM registry.fedoraproject.org/fedora-minimal:${BUILDER_VERSION} AS builder
ARG BUILDER_VERSION
ARG REPOSITORY_COMMIT_HASH

# hadolint ignore=DL3041
RUN dnf --setopt="install_weak_deps=False" install --assumeyes \
      git \
      make \
      zip \
    && dnf clean all

WORKDIR /search-light
COPY ./patches /tmp/patches
RUN git init \
    && git remote add origin https://github.com/icedman/search-light \
    && git fetch origin "${REPOSITORY_COMMIT_HASH}" --depth=1 \
    && git checkout FETCH_HEAD \
    && git apply /tmp/patches/*.patch

RUN make build \
    && make publish

# stage 2: copy extension to distribution container.
FROM scratch

COPY --from=builder \
    /search-light/build \
    /usr/share/gnome-shell/extensions/search-light@icedman.github.com
COPY --from=builder \
    /search-light/build/schemas/org.gnome.shell.extensions.search-light.gschema.xml \
    /usr/share/glib-2.0/schemas/
