name: "Cleanup cache for closed branch"

on:
  pull_request:
    types:
      - "closed"

permissions:
  actions: "write"

jobs:
  cleanup:
    name: "Cleanup cache"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4.2.2"

      - name: "Setup gh extension `actions/gh-actions-cache`"
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh extension install actions/gh-actions-cache

      - name: "Cleanup cache"
        continue-on-error: true
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          REPOSITORY: "${{ github.repository }}"
          BRANCH: "refs/pull/${{ github.event.pull_request.number }}/merge"
        run: |
          echo "Fetching cache list..."
          CACHE_KEYS=$(
            gh actions-cache list \
              -R "${REPOSITORY}" \
              -B "${BRANCH}" \
            | cut -f 1
          )

          set -e
          echo "Deleting cache..."
          for key in ${CACHE_KEYS}; do
            gh actions-cache delete "${key}" \
              -R "${REPOSITORY}" \
              -B "${BRANCH}" \
              --confirm
          done
          echo "Done"
