#!/usr/bin/env bash
set -o "errexit" -o "nounset" -o "pipefail"

FLATPAK_BUNDLE_DIR="/usr/share/flatpak/bundles"

find "${FLATPAK_BUNDLE_DIR}" -type "f" -path "*.flatpak" -print0 \
| xargs --null --replace="@" \
  flatpak install --user --bundle --assumeyes --or-update @
